### ISSUE TITLE
When i click Set Time button or AM/PM change Page will be reloaded

### ISSUE THREAD

**Issue by Parthiban130487** [DanielYKPan/ng2-date-time-picker#12]
i added control in angular 2 html page and open when i select date and click confirm date will be updated in my input box. when i select picker and change time and click set time button page will be reloaded.

html:

<input class="picker-input" [ngModel]="fromDt" [returnObject]="'string'" [viewFormat]="'MM/DD/YYYY hh:mm A'" [(dateTimePicker)]="fromDt" [hourTime]="'12'" [mode]="'dropdown'" readonly>

![image](https://cloud.githubusercontent.com/assets/26784314/24487988/68e6e654-1531-11e7-812e-4ca0c4267f33.png)

**Comment by DanielYKPan** [comment]
@Parthiban130487 
Normally, when you click 'Set Time', it will go back to the calendar. And when you click confirm, it will close the picker.

**Comment by timmyrosen** [comment]
#14 I opened a pull request to solve this.

**Comment by DanielYKPan** [comment]
@timmyrosen 
Ah~~~I see....that's a scenario I didn't test....
Thanks man, I will look at it right away....

**Comment by Parthiban130487** [comment]
Thank you, it's now working for me..
