### ISSUE TITLE
Override Css 

### ISSUE THREAD

**Issue by jeromehenry** [DanielYKPan/ng2-date-time-picker#13]
![image](https://cloud.githubusercontent.com/assets/26215036/24490708/72f2fbe6-1541-11e7-879f-265dc1836b87.png)
The dropdown is too large. how to override the css  and disable the day feature of the component?

Thank you .

**Comment by DanielYKPan** [comment]
@jeromehenry 

Update to ng2-date-time-picker@2.1.0

The picker width has been updated. Right now it should be alright.

If you only want to use the time-picker, set [pickerType] = " 'time' "

Have fun.
