### ISSUE TITLE
Not able to Run the date-time-picker 

### ISSUE THREAD

**Issue by Avneets** [DanielYKPan/ng2-date-time-picker#17]
Hi ,
I am using angular cli but not able to run the same.
Following is my error 

Can't bind to 'dateTimePicker' since it isn't a known property of 'input'. ("<input [ngModel]="momentValue | date: 'short'" [ERROR ->][(dateTimePicker)]="momentValue" readonly />")

**Comment by DanielYKPan** [comment]
@Avneets 
Did you import the DateTimePicker module into your app.module?

**Comment by Avneets** [comment]
Yes i have imported the same in my app.module.ts still it gives me an error.

**Comment by DanielYKPan** [comment]
@Avneets 
Is your component in the same module of your app module?

**Comment by Avneets** [comment]
Yes. Its not able to find the directive.

**Comment by DanielYKPan** [comment]
@Avneets 
Not sure what the problem is. But I just download a new angular cli package, and test it. It works well.

**Comment by Avneets** [comment]
Thanks. Really appreciate your help. I just wanted to check if i need to import moment using the
Import {Moment} from 'moment/moment/' ? 
It was giving me an error on 
this. momentValue=moment so i created 
Private moment:any
Is this a problem?

**Comment by DanielYKPan** [comment]
are u running your app in SystemJS or Webpack?

**Comment by Avneets** [comment]
I am running it on the Webpack.

**Comment by DanielYKPan** [comment]
@Avneets 
If you running on the webpack, you don't need to import MomentJs.

**Comment by Avneets** [comment]
Ohh.. Then is my declaration of 
Private momentValue:any; correct?

**Comment by DanielYKPan** [comment]
@Avneets 
I could not tell as I was not familiar with ur project.
Just follow my example in README, and it should be alright.
Thanks.

**Comment by Avneets** [comment]
Yes it finally worked . Thanks again for the help. Even i have no idea what the issue was. :)
