### ISSUE TITLE
Modal Class

### ISSUE THREAD

**Issue by enyachoke** [DanielYKPan/ng2-date-time-picker#2]
Using the .modal class will clash with other frameworks like bootstrap.

**Comment by DanielYKPan** [comment]
Hi, @enyachoke 

Is it because the name of the .modal component or others?
Can you be more specific about the clash with bootstrap please?
How about give me your project basic set up, and I will try to duplicate your scenario and fix the problem.

**Comment by enyachoke** [comment]
https://github.com/DanielYKPan/ng2-date-time-picker/blob/master/src/date-time-picker/picker-modal/modal.component.scss#L15

If you include bootstrap css to your project the modal will not work.

**Comment by DanielYKPan** [comment]
Ok, I see.
That's the name conflict. I will change the css name and fix the problem. 
Thanks you.

**Comment by DanielYKPan** [comment]
Hi, @enyachoke

the modal name conflict with bootstrap has fixed. Feel free to try it, and let me know if it works.
Right now i am closing this issue.
