### ISSUE TITLE
ERROR in DateTimePickerModule is not an NgModule

### ISSUE THREAD

**Issue by jigsshah** [DanielYKPan/ng2-date-time-picker#6]
hello,
while importing this plugin into my app.module.ts gives me the following error:
ERROR in DateTimePickerModule is not an NgModule.

**Comment by jurafa** [comment]
Same for me with version 2.0.0 and higher. 
Version 1.0.7 compiles without problem.
I am using angular/cli with webpack.

**Comment by DanielYKPan** [comment]
@jigsshah @jurafa 
I will check for it...

@jigsshah are you running it using SystemJS or Webpack?

**Comment by DanielYKPan** [comment]
@jigsshah @jurafa 
I looked for the problems you both mentioned.
You may running your app with **Angular JS Version 4.0.0**. That may be the reason getting the error:
ERROR in DateTimePickerModule is not an NgModule.

Currently, this package only supports the **AngularJS Version 2.*.***

@jigsshah 
Are you using this [angular/cli](https://github.com/angular/angular-cli). It is running the **Angular JS Version 4.0.0**. That is the reason getting the error.

Thanks guys. I will update this package to Angular JS 4.0.0 today, and let you guys know when it is completed.

**Comment by DanielYKPan** [comment]
@jigsshah @jurafa 
I looked for the problem you mentions. And I found some packages building with Angular 2 have the some problem too. I found [this one](https://github.com/rnadler/ng2-password-strength-bar/issues/6).

I will look at it and try to fix it today. 
Thanks guys.

**Comment by jigsshah** [comment]
Hello Daniel,
First of all thanks for you looking to issue and providing your time.
My Angular version is angular/compiler-cli": "^2.3.1" and i am using SystemJS Package Loader

**Comment by DanielYKPan** [comment]
@jigsshah 
Yes, I found the problem similar to other angular2 package like [this one](https://github.com/rnadler/ng2-password-strength-bar/issues/6). I am working on it right now.

**Comment by jigsshah** [comment]
Hello Daniel,
Can you let me know if we can have or use the existing plugin in the inline mode also as like bootstrap one like.
Thanks

**Comment by DanielYKPan** [comment]
@jigsshah @jurafa 
Guys, I fixed the problem. Please update the package to version 2.0.8.

@jurafa 
If you running the package in the latest [angular-cli](https://github.com/angular/angular-cli), this package still would not work. This is because the latest angular/cli is running the AngularJS 4.0.0, and AngularJS 4.0.0 animation has its own module (not in @angular/core any more). This causes the package crash. I would create a new **ng4-date-time-picker** package.

**Comment by jurafa** [comment]
Thank you for your time.
I am using Angular 2 with WebPack. I will try the fix soon.
BTW: The naming conventions have slightly changed and naming package ng*-date-time-picker is not recommended anymore according to this: http://angularjs.blogspot.cz/2016/12/ok-let-me-explain-its-going-to-be.html (Quote: "Also, we should start avoiding GitHub/NPM libraries prefixed with ng2- or angular2-.")
