### ISSUE TITLE
How to import scss variables to override

### ISSUE THREAD

**Issue by jstoup111** [DanielYKPan/ng2-date-time-picker#7]
I'm sure there's an easy way to do this that I'm just not figuring out. I've added this to an Ionic 2 project, and as far as I can tell, there isn't a way to change the scss variables to theme the popup differently.

If there is can you point me towards how to do this?

**Comment by DanielYKPan** [comment]
@jstoup111 you mean you want to change the popup animation?

**Comment by DanielYKPan** [comment]
@jstoup111 
Or do you mean you want to change the popup mode theme such as the color, the bg color and the font size?

If you want to change the theme color,  the current version does not support this yet. But I would create a variables in the next update, hopefully that could let people configure the theme color.
Thanks for you advice.

**Comment by DanielYKPan** [comment]
@jstoup111 
I added [theme] to change the theme color. The default color is 'blue'. Another colors include 'green', 'teal', 'cyan', 'grape', 'red', 'gray'. Just add [theme=" 'grape '"], and the theme color would change.
