### ISSUE TITLE
Optional AM/PM mode

### ISSUE THREAD

**Issue by marty912** [DanielYKPan/ng2-date-time-picker#9]
Hello again, 

In french (and others locales), we don't use this AM/PM mechanism and we have 24 hours system instead. 
Do you think it could be an option of your component ?

Sincerely yours, 

Marty

**Comment by DanielYKPan** [comment]
Cool,
I will implement this option right away. In this package version 1.*, I did have this 24hours/12hours option.

Thanks for your advice.

**Comment by DanielYKPan** [comment]
It has been added the optional variable [hourTime].

The default value is '12'. This means the hourTime format is 12-hour format. The other option is '24'.
Check more inform on README.md.
